### ISSUE TITLE
Consider making Yaml enum pub

### ISSUE THREAD

**Issue by Gozala** [azdle/rust-frontmatter#1]
Hi,

Parsed data and specifically hash-map (which is what I think what frontmatter would always produce) can not be used without Yaml enum. It also appears that version used here is pretty out of date, which in turn requires ensuring that there is no mismatch  between yaml-rust added to dependencies and one used by this library.

I would propose making `Yaml` enum pub so users do not need to deal with additional deps.

**Comment by softprops** [comment]
I just hit this problem the latest yaml-rust is not compatible with this crate. One alternative would be to push a release making it so. Another would be to re-export Yaml. If this lib is aiming for low maintenance, re-exporting Yaml would probably be best

**Comment by azdle** [comment]
I've published 0.3.1 that re-exports `Yaml` so you can use it directly and I've also published `0.4.0` that then updates to yaml-rust 0.4.

I've given this library basically zero thought since I first published it 4 years ago as a learning exercise, there's probably lots that could be improved about it. PRs are very welcome if anyone wants to improve it.

**Comment by softprops** [comment]
@azdle thanks!

**Comment by softprops** [comment]
4 years... It still works great
